
<?php require_once "./tem/header.phtml"?>

<form action="formservice" method="GET">
    <label for="id_vehiculo">Id vehiculo</label>
    <input name="id_vehiculo" id="id_vehiculo" type="number">

    <label for="id_mecanico">Id mecanico</label>
    <input name="id_mecanico" id="id_mecanico" type="number">

    <label for="fecha">fecha</label>
    <input name="fecha" id="fecha" type="date">

    
    <label for="kilometraje" >kilometraje</label>
    <input name="kilometraje" id="kilometraje" type="number">

    <button type="submit">Agregar</button>
</form>