<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Musimundo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Concesionaria Claudio Zabala</a>
        <?php if ($this->usuarios): ?>
    <span style="color: red;"><?= $this->usuarios->nombre ?></span>
<?php else: ?>
    <span style="color: red;">Anonimo</span>
<?php endif; ?>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>services">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>vehiculos">Vehiculos</a>
          </li>
          <li class="nav-item">
            <?php if ($this->usuarios): ?>
              <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>desloguearse">Cerrar Sesion</a>
            <?php else: ?>
              <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>formLogin">Iniciar Sesion</a>
            <?php endif; ?>
          </li>
        </ul>
      </div>
      </div>
    </nav>
  </header>

</body>

</html>